### ISSUE TITLE
Snooze duration resets to 5 min when snoozing

### ISSUE THREAD

**Issue by johnsgp** [amrmsaraya/clock#1]
I'm using version 1.0.5 (6) on Android 11.

**Setup**: add a new alarm, set to 1 minute in the future.  Change snooze to 15 minutes and save. When the alarm rings, tap to snooze it.

**Expected**: alarm snoozes for 15 minutes

**Actual**: alarm snoozes for 5 minutes, and the setting for snooze changes to 5 minutes.

**Comment by amrmsaraya** [comment]
Thanks for reporting this bug @johnsgp , i will work on a fix once i have a free time

**Comment by johnsgp** [comment]
@amrmsaraya I have a possible fix for this and would like to offer a pull request. Is that something you would like? I'm asking because there is no license information so I'm unsure.

**Comment by amrmsaraya** [comment]
Sure, feel free to add a pull request
